# Generated by Django 4.1.2 on 2022-11-14 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.order'),
        ),
    ]
