# Generated by Django 4.1.2 on 2022-11-14 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_profile_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='product_inventory',
        ),
    ]
