# Generated by Django 4.1.2 on 2022-10-19 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_product_category_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='product_inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='media_product', to='inventory.product'),
            preserve_default=False,
        ),
    ]
