# Generated by Django 4.1.2 on 2022-10-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_media_product_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(default=123, upload_to='images/'),
        ),
    ]
