# Generated by Django 4.1.2 on 2022-11-14 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_remove_profile_order_order_owner_alter_media_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order', to='inventory.profile'),
        ),
    ]
