# Generated by Django 4.1.2 on 2022-11-13 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_comment_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
